import { InventoryItem, SaleRecord, Notification, Supplier, Warehouse } from './types';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    inventory: 'Stock Inventory',
    label_printing: 'Scan & Print',
    sales: 'Sales History',
    architecture: 'System Architecture',
    procurement: 'Procurement',
    warehouse_menu: 'Warehouse Ops',
    settings: 'System Settings',
    shift: 'Shift: Morning',
    online: 'Online',
    search_placeholder: 'Search products by name, SKU, or barcode...',
    sync: 'Sync',
    add_item: 'Add Item',
    product_name: 'Product Name',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    status: 'Status',
    out_of_stock: 'Out of Stock',
    low_stock: 'Low Stock',
    good: 'Good',
    todays_sales: "Today's Sales",
    revenue: 'Total Revenue',
    transactions: 'Transactions',
    ask_ai: 'Ask Assistant',
    quick_lookup: 'Quick Lookup',
    notifications: 'Notifications',
    close: 'Close',
    mark_read: 'Mark all as read',
    store_name: 'Store Name',
    register_id: 'Device ID',
    enable_sound: 'Enable Sound Effects',
    save_changes: 'Save Changes',
    language: 'Language',
    lookup_title: 'Item Lookup',
    lookup_desc: 'Scan or type barcode/shelf tag to find item details.',
    lookup_input: 'Enter Barcode, SKU, or Shelf Tag...',
    company: 'Company/Brand',
    shelf_tag: 'Shelf Tag',
    barcode: 'Barcode',
    item_details: 'Item Details',
    add_item_title: 'Add / Edit Product',
    sku: 'SKU',
    save_product: 'Save Product',
    syncing: 'Syncing...',
    synced: 'Synced!',
    scan_mode: 'Scan Mode',
    mode_barcode: 'Product Barcode',
    mode_shelftag: 'Shelf Tag',
    scan_input_placeholder: 'Scan or type code here...',
    item_found: 'Item Found',
    add_to_print_queue: 'Add to Print Queue',
    print_label: 'Print Label',
    print_queue: 'Print Queue',
    clear_queue: 'Clear',
    print_all: 'Print All',
    no_items_queue: 'No items in print queue',
    preview: 'Label Preview',
    printing: 'Printing...',
    last_updated: 'Last Updated',
    actions: 'Actions',
    delete: 'Delete',
    edit: 'Edit',
    cancel: 'Cancel',
    confirm_delete: 'Are you sure you want to delete this item?',
    currency: 'Currency',
    currency_placeholder: 'e.g. USD, KWD, EGP',
    // New Translations
    purchase_request: 'Purchase Request',
    purchase_order: 'Purchase Order',
    supplier_invoice: 'Supplier Invoice',
    grn: 'Goods Receipt (GRN)',
    stock_transfer: 'Stock Transfer',
    returns: 'Returns',
    create_new: 'Create New',
    approve: 'Approve',
    reject: 'Reject',
    verify: 'Verify Stock',
    post_invoice: 'Post Invoice',
    download_json: 'Download JSON',
    view_document: 'View/Print',
    supplier: 'Supplier',
    warehouse: 'Warehouse',
    source: 'Source',
    destination: 'Destination',
    date: 'Date',
    total_amount: 'Total Amount',
    items: 'Items',
    reason: 'Reason',
    reference: 'Reference',
    three_way_match: '3-Way Match',
    match_success: 'Matched',
    match_fail: 'Mismatch',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    inventory: 'المخزون',
    label_printing: 'المسح والطباعة',
    sales: 'سجل المبيعات',
    architecture: 'هيكل النظام',
    procurement: 'المشتريات',
    warehouse_menu: 'المستودع',
    settings: 'إعدادات النظام',
    shift: 'الوردية: صباحية',
    online: 'متصل',
    search_placeholder: 'بحث باسم المنتج، الرمز، أو الباركود...',
    sync: 'مزامنة',
    add_item: 'إضافة صنف',
    product_name: 'اسم المنتج',
    category: 'الفئة',
    price: 'السعر',
    stock: 'المخزون',
    status: 'الحالة',
    out_of_stock: 'نفذت الكمية',
    low_stock: 'مخزون منخفض',
    good: 'متوفر',
    todays_sales: 'مبيعات اليوم',
    revenue: 'إجمالي الإيرادات',
    transactions: 'المعاملات',
    ask_ai: 'المساعد الذكي',
    quick_lookup: 'بحث سريع',
    notifications: 'الإشعارات',
    close: 'إغلاق',
    mark_read: 'تحديد الكل كمقروء',
    store_name: 'اسم المتجر',
    register_id: 'رقم الجهاز',
    enable_sound: 'تفعيل المؤثرات الصوتية',
    save_changes: 'حفظ التغييرات',
    language: 'اللغة',
    lookup_title: 'بحث عن صنف',
    lookup_desc: 'امسح أو اكتب الباركود/رقم الرف لعرض التفاصيل.',
    lookup_input: 'أدخل الباركود، الرمز، أو رقم الرف...',
    company: 'الشركة/العلامة التجارية',
    shelf_tag: 'رقم الرف',
    barcode: 'الباركود',
    item_details: 'تفاصيل الصنف',
    add_item_title: 'إضافة / تعديل منتج',
    sku: 'الرمز (SKU)',
    save_product: 'حفظ المنتج',
    syncing: 'جاري المزامنة...',
    synced: 'تمت المزامنة!',
    scan_mode: 'وضع المسح',
    mode_barcode: 'باركود المنتج',
    mode_shelftag: 'ملصق الرف',
    scan_input_placeholder: 'امسح أو اكتب الرمز هنا...',
    item_found: 'تم العثور على الصنف',
    add_to_print_queue: 'إضافة لقائمة الطباعة',
    print_label: 'طباعة الملصق',
    print_queue: 'قائمة الطباعة',
    clear_queue: 'مسح',
    print_all: 'طباعة الكل',
    no_items_queue: 'القائمة فارغة',
    preview: 'معاينة الملصق',
    printing: 'جاري الطباعة...',
    last_updated: 'آخر تحديث',
    actions: 'إجراءات',
    delete: 'حذف',
    edit: 'تعديل',
    cancel: 'إلغاء',
    confirm_delete: 'هل أنت متأكد من حذف هذا الصنف؟',
    currency: 'العملة',
    currency_placeholder: 'مثال: د.ك، ج.م، $',
    purchase_request: 'طلب شراء',
    purchase_order: 'أمر شراء',
    supplier_invoice: 'فاتورة مورد',
    grn: 'إذن استلام (GRN)',
    stock_transfer: 'تحويل مخزون',
    returns: 'مرتجعات',
    create_new: 'إنشاء جديد',
    approve: 'اعتماد',
    reject: 'رفض',
    verify: 'تأكيد المخزون',
    post_invoice: 'ترحيل الفاتورة',
    download_json: 'تحميل JSON',
    view_document: 'عرض/طباعة',
    supplier: 'المورد',
    warehouse: 'المستودع',
    source: 'المصدر',
    destination: 'الوجهة',
    date: 'التاريخ',
    total_amount: 'الإجمالي',
    items: 'الأصناف',
    reason: 'السبب',
    reference: 'المرجع',
    three_way_match: 'مطابقة ثلاثية',
    match_success: 'متطابق',
    match_fail: 'غير متطابق',
  }
};

export const MOCK_INVENTORY: InventoryItem[] = [
    { id: '1', name: 'Organic Milk', sku: 'DAIRY-001', barcode: '123456789', shelfTag: 'A-01', company: 'FarmFresh', category: 'Dairy', stockLevel: 50, price: 2.50, lastUpdated: new Date().toISOString() },
    { id: '2', name: 'Whole Wheat Bread', sku: 'BAK-002', barcode: '987654321', shelfTag: 'B-02', company: 'BakeryCorp', category: 'Bakery', stockLevel: 20, price: 3.00, lastUpdated: new Date().toISOString() },
];

export const MOCK_SALES: SaleRecord[] = [];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: '1', title: 'System', message: 'Welcome to NextERP.', time: 'Just now', read: false },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
    { id: 'wh-main', name: 'Main Distribution Center', location: 'Industrial Zone A' },
    { id: 'wh-downtown', name: 'Downtown Store', location: 'City Center' },
    { id: 'wh-north', name: 'North Branch', location: 'North District' }
];

export const MOCK_SUPPLIERS: Supplier[] = [
    { id: 'sup-1', name: 'Acme Global Foods', code: 'SUP-001', currency: 'USD', paymentTerms: 'Net 30', contactEmail: 'orders@acme.com' },
    { id: 'sup-2', name: 'Fresh Farms Ltd', code: 'SUP-002', currency: 'USD', paymentTerms: 'Immediate', contactEmail: 'sales@freshfarms.com' },
    { id: 'sup-3', name: 'Tech Packagings', code: 'SUP-003', currency: 'USD', paymentTerms: 'Net 60', contactEmail: 'invoice@techpack.com' }
];